.PHONY: all setpermissions

all: setpermissions

setpermissions:
	@echo "+-----------------------------------------------------------+"
	@echo "| setting permissions of the start scripts (Python scripts) |"
	@echo "+-----------------------------------------------------------+"
		chmod 777 prep_test_env.py
		chmod 777 start_config_editor.py
		#chmod 777 start_editor.py
		chmod 777 start_poolviewer.py
		chmod 777 start_simulators.py

