#--------------------------------------------
# Name: BasicBsw
# Title: Basic Operation Under BSW Control
# Author: PnP
#--------------------------------------------

# Description: Switch on instrument to remain under BSW control, perform basic 
#              checks on its operation under nominal conditions and then switch 
#              instrument off 

# Precondition: Instrument switched off and configured to remain under BSW control 

#--------------------------------------------
# STEP 100 - Instrument Switch-On
# Run the FCP InstSwitchOnCoc (Instrument Switch-On for CoCa) to start the BSW
# in MAINTENANCE Mode
#
# Node N1: Send TC(131,4) to platform to set instrument in 'CheckOut' state
# Node N3: Send TC(131,1) to platform to switch on instrument

# WAIT FcpPwrOnChkOutT2 sec (see sect. 6 of [FcpDef] for value of FcpPwrOnChkOutT2)
# VERIFY that instrument TM is generated

#--------------------------------------------
# STEP 200 - Instrument Switch-On
# Run the FCP CometIntFcp:CheckConfig to verify the BSW configuration 
#
# NODE N25: Collect BSW1 version from Bsw1ActVersion in HK report HkBswBasicRep
# VERIFY that the value of Bsw1ActVersion matches the version of the BSW_1 image 
#        currently installed on the instrument as it is given in the Software
#        Configuration File (SCF)

# NODE N17: Collect BSW2 version from BswActVersion and BswImageType in HkBswBasicRep 
#           packet 
# VERIFY that the value of BswImageType is CUSTOM_L indicating that the currently 
#        running image is the "CUstom Image from the Live Area"
# VERIFY that the value of BswActVersion matches the version of the Custom BSW_2
#        currently installed on the instrument as it is given in the Software
#        Configuration File (SCF)

# NODE N22: Collect values of BSW_1 and BSW_2 Boot Descriptor parameters from 
#           HkBswBasicRep packet

# NODE N23: Send TC(166,21) command and collect BSW_1 and BSW_2 Boot Descriptor 
#           parameters mapped to context variables from TM(166,22) (see table 149 
#           in appendix F of TM/TC ICD)
cfl.Tcsend_DB('L166021RepCtx', pool_name='LIVE')

#--------------------------------------------
# STEP 300 - Basic BSW Telemetry Checks
# VERIFY that:
#        (a) The BSW is in MAINTENANCE Mode (CocOperationMode == MAINTENANCE in
#            packet HkBswBasicRep)
#        (b1)The synchronization word in the TM Secondary Header (TIMESYNC) indicates
#            that the instrument is synchronized and the time-stamp is consistent
#            with the platform time
#        (b2)Event EVT_SYNCH_ACQ was generated within 1 second from start-up
#        (c) Telemetry packet HkBswBasicRep is generated with the period 5 sec
#        (e) The watchdog is disabled (LowWdEnabled is DISABLED in HkBswBasicRep)
#        (f) All error counters in HkBswBasicRep are set to zero (FdScrubDbeNmb,
#            FdScrubSbeNmb, Ver*Fail*, Mon*Err
#        (g) The SID of packet HkBswBasicRep is 7001

#--------------------------------------------
# STEP 400 - Perform Connection Test
# Send command Tst:Cnct and verify that report Tst:CnctRep is generated within 
# 100 ms from the reception of the command 
cfl.Tcsend_DB('L017001PerfConnTest', pool_name='LIVE')

# VERIFY that TM(17,2) is generated within 100 ms of TC(17,1)

#--------------------------------------------
# STEP 500 - Acquire and Check Boot Report
# Run FCP CometIntFcp:TrigBootRep to trigger generation of the boot report 
cfl.Tcsend_DB('L170010GenBootRep', pool_name='LIVE')

# VERIFY that TM(170,11) TmBootRep is generated within 100 ms of TC(170,10)
# VERIFY that the reset type information in the boot report is consistent 
#        with the instrument having been powered up (i.e. RstTypeRtIn is equal
#        to PLTFRM_PW_OFF
# VERIFY that the context information is all zero (instrument was powered up) 

#--------------------------------------------
# STEP 700 - Telemetry Jitter and Sequence Counters
# Collect a periodically generated TM packet for 20 minutes 

# VERIFY that the time-stamp of the first and the last packets differ by no 
#        more than 20 min + 10 ms
# VERIFY that the maximum jitter on the time-stamps is below 10 ms
# VERIFY that there are no gaps in the sequence counters of the packets 

#--------------------------------------------
# STEP 800 - Instrument Switch-Off
# Run the FCP CometIntFcp:InstSwitchOff to switch off the instrument from 
# Boot Mode
# NODE N1: Send TC(131,2) to platform to power off insturment

# VERIFY that no more telemetry is generated by instrument



