"""
SMIEL SXI science meta data structure definitions
"""

import ctypes


FMT_LUT = {'UINT8': '>u1',
           'B': '>u1',
           'uint1': '>u1',
           'uint2': '>u1',
           'uint3': '>u1',
           'uint4': '>u1',
           'uint5': '>u1',
           'uint6': '>u1',
           'uint7': '>u1',
           'UINT16': '>u2',
           'H': '>u2',
           'UINT32': '>u4',
           'I': '>u4',
           'INT8': '>i1',
           'b': '>i1',
           'INT16': '>i2',
           'h': '>i2',
           'INT32': '>i4',
           'i': '>i4',
           'FLOAT': '>f8',
           'f': '>f8',
           'd': '>f8',
           'CUC918': '>f8',
           'I24': '>S3',
           'S8': '>S8',
           'S10': '>S10'}

STRUCT_CE_HEADER = [
    ("version_number", ctypes.c_uint16),
    ("build_number", ctypes.c_uint16),
    ("sdp_version", ctypes.c_uint16),
    ("coarse", ctypes.c_uint32),
    ("fine", ctypes.c_uint16),
    ("obsid", ctypes.c_uint32),
    ("ce_counter", ctypes.c_uint16),
    ("sdp_group_members", ctypes.c_uint16),
    ("ce_size", ctypes.c_uint32),
    ("ce_key", ctypes.c_uint32),
    ("product", ctypes.c_uint8),
    ("ce_integrity", ctypes.c_uint8),
    ("group_meta_size", ctypes.c_uint16),
    ("frame_meta_size", ctypes.c_uint16),
    ("compressed_meta_size", ctypes.c_uint16),
    ("data_size", ctypes.c_uint32),
    ("compressed_data_size", ctypes.c_uint32)
]

GROUP_TABLE_STRUCT = [('groupIdx', 'UINT16'),
                      ('timetag', 'FLOAT'),
                      ('obsid', 'UINT32'),
                      ('ceCounter', 'UINT16'),
                      ('sdpGroupMembers', 'UINT32'),
                      ('ceSize', 'UINT32'),
                      ('ceKey', 'S8'),
                      ('product', 'UINT8'),
                      ('ceIntegrity', 'UINT8'),
                      ('groupMetaSize', 'UINT32'),
                      ('frameMetaSize', 'UINT32'),
                      ('compressedMetaSize', 'UINT32'),
                      ('dataSize', 'UINT32'),
                      ('compressedDataSize', 'UINT32'),
                      ('FRMccd2EPixThreshold', 'H'),
                      ('FRMccd2FPixThreshold', 'H'),
                      ('FRMccd2Readout', 'B'),
                      ('FRMccd4EPixThreshold', 'H'),
                      ('FRMccd4FPixThreshold', 'H'),
                      ('FRMccd4Readout', 'B'),
                      ('FRMccdMode2Config', 'B'),
                      ('FRMccdModeConfig', 'B'),
                      ('FRMchargeInjectionEn', 'B'),
                      ('FRMchargeInjectionGap', 'H'),
                      ('FRMchargeInjectionWidth', 'H'),
                      ('FRMcorrectionBypass', 'B'),
                      ('FRMcorrectionType', 'B'),
                      ('FRMeduWanderingMaskEn', 'B'),
                      ('FRMeventDetection', 'B'),
                      ('FRMimgClkDir', 'B'),
                      ('FRMintSyncPeriod', 'I'),
                      ('FRMpixOffset', 'h'),
                      ('FRMreadoutNodeSel', 'B'),
                      ('sdpDiffAxis', 'B'),
                      ('sdpDiffMethod', 'B'),
                      ('EvtBadPixelCount', 'I'),
                      ('EvtFilterCount1', 'I'),
                      ('EvtFilterCount2', 'I'),
                      ('EvtFilterCount3', 'I'),
                      ('EvtFilterN', 'H'),
                      ('EvtFilterThr1', 'H'),
                      ('EvtFilterThr2', 'H'),
                      ('EvtFilterThr3', 'H'),
                      ('FeeBadPixelFilter', 'B'),
                      ('FeeEventFilterEnable', 'B'),
                      ('sdpAriPar1', 'I'),
                      ('sdpAriPar2', 'I'),
                      ('sdpBinX', 'H'),
                      ('sdpBinY', 'H'),
                      ('sdpCropB', 'H'),
                      ('sdpCropT', 'H'),
                      ('sdpCropX', 'H'),
                      ('sdpCropY', 'H'),
                      ('sdpDecimN', 'I'),
                      ('sdpEvtCeil', 'H'),
                      ('sdpEvtCtr', 'I'),
                      ('sdpEvtFloor', 'H'),
                      ('sdpGolombPar1', 'I'),
                      ('sdpGolombPar2', 'I'),
                      ('sdpOffsetSignal', 'h'),
                      ('NOfEvtDet', 'H'),
                      ('FRMeventPktLimit', 'I'),
                      ('FRMdgEn', 'B'),
                      ('FRMregClkDir', 'B'),
                      ('FRMtrapPumpDwellTerm', 'I'),
                      ('FRMparallelToiPeriod', 'H'),
                      ('FRMparallelClkOverlap', 'H'),
                      ('FRMtrapPumpingShuffleCou', 'H'),
                      ('FRMreadoutPauseCounter', 'H'),
                      ('FRMvStart', 'H'),
                      ('FRMvEnd', 'H'),
                      ('FRMhStart', 'H'),
                      ('FRMhEnd', 'H')]

FRAME_TABLE_STRUCT = [('AdcTempCcd', 'H'),
                    ('FrameDiscardCount', 'I'),
                    ('LastFrameEvtCount', 'I'),
                    ('FRMHK1v2dMon', 'H'),
                    ('FRMHK2v5aMon', 'H'),
                    ('FRMHK2v5dMon', 'H'),
                    ('FRMHK3v3bMon', 'H'),
                    ('FRMHK3v3dMon', 'H'),
                    ('FRMHK5vbNegMon', 'H'),
                    ('FRMHK5vbPosMon', 'H'),
                    ('FRMHK5vrefMon', 'H'),
                    ('FRMHKboardId', 'B'),
                    ('FRMHKccd2EPixFullSun', 'H'),
                    ('FRMHKccd2FPixFullSun', 'H'),
                    ('FRMHKccd2TsA', 'H'),
                    ('FRMHKccd2VddMon', 'H'),
                    ('FRMHKccd2VgdMon', 'H'),
                    ('FRMHKccd2VodMonE', 'H'),
                    ('FRMHKccd2VodMonF', 'H'),
                    ('FRMHKccd2VogMon', 'H'),
                    ('FRMHKccd2VrdMonE', 'H'),
                    ('FRMHKccd2VrdMonF', 'H'),
                    ('FRMHKccd4EPixFullSun', 'H'),
                    ('FRMHKccd4FPixFullSun', 'H'),
                    ('FRMHKccd4TsB', 'H'),
                    ('FRMHKccd4VddMon', 'H'),
                    ('FRMHKccd4VgdMon', 'H'),
                    ('FRMHKccd4VodMonE', 'H'),
                    ('FRMHKccd4VodMonF', 'H'),
                    ('FRMHKccd4VogMon', 'H'),
                    ('FRMHKccd4VrdMonE', 'H'),
                    ('FRMHKccd4VrdMonF', 'H'),
                    ('FRMHKcmicCorr', 'H'),
                    ('FRMHKerrorFlags', 'I'),
                    ('FRMHKfpgaMajorVersion', 'B'),
                    ('FRMHKfpgaMinorVersion', 'B'),
                    ('FRMHKfpgaOpMode', 'B'),
                    ('FRMHKframeCounter', 'H'),
                    ('FRMHKigHiMon', 'H'),
                    ('FRMHKprt1', 'H'),
                    ('FRMHKprt2', 'H'),
                    ('FRMHKprt3', 'H'),
                    ('FRMHKprt4', 'H'),
                    ('FRMHKprt5', 'H'),
                    ('FRMHKspwStatus', 'I'),
                    ('FRMHKvan1PosRaw', 'H'),
                    ('FRMHKvan2PosRaw', 'H'),
                    ('FRMHKvan3NegMon', 'H'),
                    ('FRMHKvccd', 'H'),
                    ('FRMHKvccdPosRaw', 'H'),
                    ('FRMHKvclkPosRaw', 'H'),
                    ('FRMHKvdigRaw', 'H'),
                    ('FRMHKviclk', 'H'),
                    ('FRMHKvrclkMon', 'H'),
                    ('sdpProductStarttimeCrs', 'I'),
                    ('sdpProductStarttimeFine', 'I'),
                    ('RseShutSts', 'B'),
                    ('SPWPktDrop', 'H'),
                    ('groupIdx', 'H')]

META_GROUP_ITEMS = [('FRMccd2EPixThreshold', 'H'),
                    ('FRMccd2FPixThreshold', 'H'),
                    ('FRMccd2Readout', 'B'),
                    ('FRMccd4EPixThreshold', 'H'),
                    ('FRMccd4FPixThreshold', 'H'),
                    ('FRMccd4Readout', 'B'),
                    ('FRMccdMode2Config', 'B'),
                    ('FRMccdModeConfig', 'B'),
                    ('FRMchargeInjectionEn', 'B'),
                    ('FRMchargeInjectionGap', 'H'),
                    ('FRMchargeInjectionWidth', 'H'),
                    ('FRMcorrectionBypass', 'B'),
                    ('FRMcorrectionType', 'B'),
                    ('FRMeduWanderingMaskEn', 'B'),
                    ('FRMeventDetection', 'B'),
                    ('FRMimgClkDir', 'B'),
                    ('FRMintSyncPeriod', 'I'),
                    ('FRMpixOffset', 'h'),
                    ('FRMreadoutNodeSel', 'B'),
                    ('sdpDiffAxis', 'B'),
                    ('sdpDiffMethod', 'B'),
                    ('EvtBadPixelCount', 'I'),
                    ('EvtFilterCount1', 'I'),
                    ('EvtFilterCount2', 'I'),
                    ('EvtFilterCount3', 'I'),
                    ('EvtFilterN', 'H'),
                    ('EvtFilterThr1', 'H'),
                    ('EvtFilterThr2', 'H'),
                    ('EvtFilterThr3', 'H'),
                    ('FeeBadPixelFilter', 'B'),
                    ('FeeEventFilterEnable', 'B'),
                    ('sdpAriPar1', 'I'),
                    ('sdpAriPar2', 'I'),
                    ('sdpBinX', 'H'),
                    ('sdpBinY', 'H'),
                    ('sdpCropB', 'H'),
                    ('sdpCropT', 'H'),
                    ('sdpCropX', 'H'),
                    ('sdpCropY', 'H'),
                    ('sdpDecimN', 'I'),
                    ('sdpEvtCeil', 'H'),
                    ('sdpEvtCtr', 'I'),
                    ('sdpEvtFloor', 'H'),
                    ('sdpGolombPar1', 'I'),
                    ('sdpGolombPar2', 'I'),
                    ('sdpOffsetSignal', 'h'),
                    ('NOfEvtDet', 'H'),
                    ('FRMeventPktLimit', 'I'),
                    ('FRMdgEn', 'B'),
                    ('FRMregClkDir', 'B'),
                    ('FRMtrapPumpDwellTerm', 'I'),
                    ('FRMparallelToiPeriod', 'H'),
                    ('FRMparallelClkOverlap', 'H'),
                    ('FRMtrapPumpingShuffleCou', 'H'),
                    ('FRMreadoutPauseCounter', 'H'),
                    ('FRMvStart', 'H'),
                    ('FRMvEnd', 'H'),
                    ('FRMhStart', 'H'),
                    ('FRMhEnd', 'H')]

META_FRAME_ITEMS = [('AdcTempCcd', 'H'),
                    ('FrameDiscardCount', 'I'),
                    ('LastFrameEvtCount', 'I'),
                    ('FRMHK1v2dMon', 'H'),
                    ('FRMHK2v5aMon', 'H'),
                    ('FRMHK2v5dMon', 'H'),
                    ('FRMHK3v3bMon', 'H'),
                    ('FRMHK3v3dMon', 'H'),
                    ('FRMHK5vbNegMon', 'H'),
                    ('FRMHK5vbPosMon', 'H'),
                    ('FRMHK5vrefMon', 'H'),
                    ('FRMHKboardId', 'B'),
                    ('FRMHKccd2EPixFullSun', 'H'),
                    ('FRMHKccd2FPixFullSun', 'H'),
                    ('FRMHKccd2TsA', 'H'),
                    ('FRMHKccd2VddMon', 'H'),
                    ('FRMHKccd2VgdMon', 'H'),
                    ('FRMHKccd2VodMonE', 'H'),
                    ('FRMHKccd2VodMonF', 'H'),
                    ('FRMHKccd2VogMon', 'H'),
                    ('FRMHKccd2VrdMonE', 'H'),
                    ('FRMHKccd2VrdMonF', 'H'),
                    ('FRMHKccd4EPixFullSun', 'H'),
                    ('FRMHKccd4FPixFullSun', 'H'),
                    ('FRMHKccd4TsB', 'H'),
                    ('FRMHKccd4VddMon', 'H'),
                    ('FRMHKccd4VgdMon', 'H'),
                    ('FRMHKccd4VodMonE', 'H'),
                    ('FRMHKccd4VodMonF', 'H'),
                    ('FRMHKccd4VogMon', 'H'),
                    ('FRMHKccd4VrdMonE', 'H'),
                    ('FRMHKccd4VrdMonF', 'H'),
                    ('FRMHKcmicCorr', 'H'),
                    ('FRMHKerrorFlags', 'I'),
                    ('FRMHKfpgaMajorVersion', 'B'),
                    ('FRMHKfpgaMinorVersion', 'B'),
                    ('FRMHKfpgaOpMode', 'B'),
                    ('FRMHKframeCounter', 'H'),
                    ('FRMHKigHiMon', 'H'),
                    ('FRMHKprt1', 'H'),
                    ('FRMHKprt2', 'H'),
                    ('FRMHKprt3', 'H'),
                    ('FRMHKprt4', 'H'),
                    ('FRMHKprt5', 'H'),
                    ('FRMHKspwStatus', 'I'),
                    ('FRMHKvan1PosRaw', 'H'),
                    ('FRMHKvan2PosRaw', 'H'),
                    ('FRMHKvan3NegMon', 'H'),
                    ('FRMHKvccd', 'H'),
                    ('FRMHKvccdPosRaw', 'H'),
                    ('FRMHKvclkPosRaw', 'H'),
                    ('FRMHKvdigRaw', 'H'),
                    ('FRMHKviclk', 'H'),
                    ('FRMHKvrclkMon', 'H'),
                    ('sdpProductStarttimeCrs', 'I'),
                    ('sdpProductStarttimeFine', 'I'),
                    ('RseShutSts', 'B')]

HEADER_KEYS_GROUP = ['TIMETAG',
                     'OBSID',
                     'CE_COUNTER',
                     'SDP_GROUP_MEMBERS',
                     'CE_SIZE',
                     'CE_KEY',
                     'PRODUCT',
                     'CE_INTEGRITY',
                     'GROUP_META_SIZE',
                     'FRAME_META_SIZE',
                     'COMPRESSED_META_SIZE',
                     'DATA_SIZE',
                     'COMPRESSED_DATA_SIZE']


_meta_group_fmt = [(x[0], FMT_LUT[x[1]]) for x in META_GROUP_ITEMS]
_meta_frame_fmt = [(x[0], FMT_LUT[x[1]]) for x in META_FRAME_ITEMS]
